### ISSUE TITLE
Allow layering buttons with images

### ISSUE THREAD

**Issue by Dekamir** [Keksuccino/FancyMenu-Support#164]
Currently: Images are over buttons in any case.
![2021-05-01_01 10 14](https://user-images.githubusercontent.com/28929300/116759050-0bdf7e80-aa1a-11eb-9919-2b6c176be85b.png)

Expected: To be able to put an image under buttons.
![2021-05-01_01 04 15](https://user-images.githubusercontent.com/28929300/116759066-1437b980-aa1a-11eb-8f3e-1386a824fff2.png)

**Comment by Keksuccino** [comment]
Hi! You mean images are always over **vanilla** buttons? You can render your layout behind vanilla objects by setting the rendering order of your layout to `background`.
In the layout editor, click on **Layout -> Properties -> Rendering Order -> Background**.

**Comment by Dekamir** [comment]
I actually noticed that feature, by mistake, 30 minutes after opening this issue.
Though it would still be a nice feature to have full control of layers, instead of Background and Foreground (I know that images can be layered independently in between themselves).

It sounds like a hassle to implement to me honestly. I know how confusing Minecraft's code is, so I'll keep my fingers crossed.

Also thank you for your kind words. It's merely a VALORANT home page clone.

**Comment by Keksuccino** [comment]
I'm very sorry, but I will not add this, because it’s not possible by how FancyMenu's customization system works. Sorry :/
