### ISSUE TITLE
Exit world Button

### ISSUE THREAD

**Issue by WildTom1** [Keksuccino/FancyMenu-Support#165]
I am making a custom menu for all of my GUIs, and in the pause, GUI doesn't have a working exit button, can it be added?

**Comment by Keksuccino** [comment]
Hi! Why is the exit button not working? You can use the vanilla quit button.

**Comment by WildTom1** [comment]
I can't get the layer option working, so I tried to make an exit button myself

**Comment by Keksuccino** [comment]
Do you mean the layout option doesn’t work? What exactly isn’t working?

**Comment by WildTom1** [comment]
I can't get any buttons that I don't create won't go above the rectangle that I've made, even with the layer option.

**Comment by Keksuccino** [comment]
You can set your layout's rendering order to **Background** to render its elements behind vanilla elements. **Layout -> Properties -> Rendering Order -> Background**

**Comment by WildTom1** [comment]
Thanks!
