### ISSUE TITLE
[1.12.2] Crash on startup.

### ISSUE THREAD

**Issue by LightDimf** [Keksuccino/FancyMenu-Support#168]
Crash on startup witout crash-report. Only report in the console and logs.

1. Launch the game.
2. See crash instantly.

Crash log:
[debug.log](https://github.com/Keksuccino/FancyMenu-Support/files/6454024/debug.log)

Screenshot:
![image](https://user-images.githubusercontent.com/71969143/117702997-e7ca2d00-b1d1-11eb-86df-93a3e1eb76ef.png)

Basic Informations:
 - OS: Windows 10
 - FancyMenu Version: 2.0.6
 - Forge Version: 14.23.5.2855
 - Minecraft Version: 1.12.2
 - Active Mods: 
![image](https://user-images.githubusercontent.com/71969143/117703547-72129100-b1d2-11eb-9826-848cb64e01f8.png)

**Comment by Keksuccino** [comment]
Hi! Sorry for the late answer.
Please check the [incompatibility list](http://fm.keksuccino.de/books/fancymenu-v20x/page/20x-incompatibility-list) for conflicts and check your RandomPatches config for correct settings to make it compatible with FM.

**Comment by Keksuccino** [comment]
Closed because no response.
