### ISSUE TITLE
[1.12.2] Crash on starting up

### ISSUE THREAD

**Issue by Landsurfer2000** [Keksuccino/FancyMenu-Support#173]
**Describe the bug**
the game closes before it can even load the game

**To Reproduce**
1. Load the pack with fancy menu, konkrete, within a modpack
2. wait a couple of seconds
3. game crashes with an exit code of -1, with critical errors

**Expected behavior**
the game to not crash

**Crash Log**
[can be found here](https://pastebin.com/E1UMdB63)

**Screenshots**
N/A

**Basic Informations (please complete the following information):**
 - OS: Windows
 - FancyMenu Version 2.0.7
 - Forge/Fabric Version 14.23.5.2855
 - Minecraft Version 1.12.2
 - Active Mods 
```minecraft,mcp,FML,forge,additionalresources,entity_culling,ivtoolkit,smoothfontcore,biometweakercore,bnbgamingcore,foamfixcore,randompatches,smoothfont,betterfarmland,additional_lights,advanced-fishing,aiimprovements,mantle,inspirations,placebo,apotheosis,applecore,aquaacrobatics,aroma1997core,aromabackup,aromabackuprecovery,crafttweaker,charset,mtlib,modtweaker,jei,athenaeum,attributefix,quark,autoreglib,backportedflora,badwithernocookiereloaded,bannerelytra,base,baubles,betteradvancements,betterplacement,bibliocraft,bookshelf,bingo,biometweaker,bnbgaminglib,bonsaitrees,bookworm,forgelin,bountiful,byx,calmdownzombieguy,gamestages,carryon,cd4017be_lib,chameleon,charm,ctm,chisel,clumps,redstoneflux,cofhcore,cofhworld,coloredredstone,colouredtooltips,consolehud,containerfix,contenttweaker,controlling,cookingforblockheads,cosmeticbeds,craftingstation,ctgui,crafttweakerjei,wanionlib,creatingtables,ctdcore,cucumber,customrecord,cyclicmagic,damagetilt,debark,defaultoptions,dimdoors,discordcraft,doubleslabs,dropt,ears,effortlessbuilding,mclib,emoticons,enchdesc,enchantmentstorage,enchcontrol,thermalfoundation,enderfuge,environs,equaldragons,extendedcrafting,fantasticlib,fastfurnace,felling,floralis,libnine,storagedrawers,fluiddrawers,fluidfunnel,fluidict,foamfix,foundry,futuremc,gamblingstyle,gottschcore,hopperducts,horsetweaks,incontrol,jmc,jmh,loottweaker,jeresources,letsencryptcraft,dogslie,libraryex,loadingscreens,lootbags,lowtechcrafting,lunatriuscore,reborncore,mainmenuscale,materialchanger,mechanics,mendingfix,mia,minestrapp,minetogether,minetogetherserver,mobbanners,mousetweaks,mzombv,namepain,naturescompass,nbtmanipulator,netherex,recipehandler,oldjava,outfox,overpoweredarmorbar,packmode,packmodemenu,packupdater,patchouli,performant,plants2,plated,plustweaks,prestige,probe,progressivebosses,traverse,pvj,quarkoddities,randomportals,randomtweaks,reagenchant,reccomplex,resonance,resourceloader,rotm,shulko,simple_trophies,sneakycurses,soundfilters,spartanshields,stackie,stonechest,stygian,surge,tbone,tellme,theaurorian,titles,toastcontrol,toolbelt,topography,toughnessbar,treasure2,treetweaker,triumph,uniquee,uppers,va,vanillafix,veining,dimstack,villagenames,villagermarket,vtt,1.13_water_mechanics,wearablebackpacks,wildlyeat,wolfarmor,phosphor-lighting,toolprogression,hookt,mysticallib,osv,unidict,mclib_core```

**Comment by Keksuccino** [comment]
Hi! This is a mod incompatibility. Probably caused by one of your core mods.
Please check the [incompatibility list](http://fm.keksuccino.de/books/fancymenu-v20x/page/20x-incompatibility-list).

**Comment by Landsurfer2000** [comment]
ah, didn't know 2.0 released! i would have assumed there were some new incompatibilities heh, my bad! i fixed my issue by changing the config in RandomPatches `patchMinecraftClass` to `false`, everything works great! thank you for the help <3
