### ISSUE TITLE
Mute main menu background music while playing intro animation

### ISSUE THREAD

**Issue by thaild912** [Keksuccino/FancyMenu-Support#176]
I tried to set up an intro with audio for my Minecraft client and realized that the menu soundtracks were able to play from the start of animation loading progress and throughout the intro. It would be great if we could mute the main menu BGM since it might clash with the custom intro's music.

**Comment by Keksuccino** [comment]
Hi! That’s already possible in the [FancyMenu settings](http://fm.keksuccino.de/books/fancymenu-v20x/page/20x-fancymenu-settings) :)
