### ISSUE TITLE
Button customization not working in CreateWorldScreen because of invisible overlapping buttons

### ISSUE THREAD

**Issue by kreezxil** [Keksuccino/FancyMenu-Support#99]
Need the option to turn off Warnings. FM is reporting offhandedly odd button overlaps. A player reported https://pastebin.pl/view/e4666cd8 and when i went to fire up dev copy of the client, i got a totally different set of warnings and it looks like it was complaining about forge buttons overlapping. https://gist.github.com/d6ef99fab07c800de5bb482baf52a537

I checked the menu i created and not one of the visible buttons are overlapping. It's hard to find invisible ones once you hide them.

So yeah, a config feature to turn off that warning would be great.

**Comment by Keksuccino** [comment]
I will add a config option to turn off warnings, but they are fired for a good reason. One of your mods seems to really mess up something and maybe tries to add buttons at totally useless coordinates.
`At: X=-1418392361 Y=-1418392496! `
I think even in 20 years we don’t have a screen that can display buttons at these coordinates :‘D The button labels aren’t set either, so These would rather be image buttons or just blank buttons without any sense.

**Comment by kreezxil** [comment]
could you add something helps reveal what mod is placing off screen buttons?

**Comment by Keksuccino** [comment]
Sadly no. It's nearly impossible to track what mod added objects to menus :/ I can add some more informations to the warning that could MAYBE help to find out which mod it is in some cases, but nothing that works 100% :/

**Comment by kreezxil** [comment]
anything will help

**Comment by kreezxil** [comment]
Did some digging. created a 1.16.3 pack with just fancy menu it, the previously reported issues of the odd warnings. Well it's still here with just fancy menu and konkrete

https://gist.github.com/56e90f40be9ee7e80711c49cb9fd1ec0

The overlapping buttons warning is come from the Singleplayer world creation screen.

and i think your mod is culprit, i'll show you.

# Before
![image](https://user-images.githubusercontent.com/3880072/97864792-ccd0aa80-1cce-11eb-9659-9d61bca3bab7.png)

# After
![image](https://user-images.githubusercontent.com/3880072/97864885-ec67d300-1cce-11eb-9876-d8383a6996f3.png)

The customize button is not there in the regular view but shows up in the create layout view

For now the kludge is define that button and move it somewhere. Which I'll Do.

**Comment by kreezxil** [comment]
oh wow, FM thinks every button on that page is overlapping

**Comment by kreezxil** [comment]
ok, i figured it out, when you click more options, the page doesn't change but the buttons do.

![image](https://user-images.githubusercontent.com/3880072/97865239-8760ad00-1ccf-11eb-84fa-f2cd32e2221f.png)

It's likely a mojang thing. They're cheating, the page has 2 button panels, the one not in use is hidden. FM doesn't realize this and assumes they're over lapping.

The easy solution for me while you render a fix is to move all the buttons on to one page if that is even possible.

**Comment by kreezxil** [comment]
so the customize button i saw earlier, wasn't yours but from that second page.

**Comment by kreezxil** [comment]
I reported this before and you said the solution was to full screen. I'm full screened and on gui 2, i have context menus going off the screen.

# before
![image](https://user-images.githubusercontent.com/3880072/97865600-11a91100-1cd0-11eb-9200-a3d4fcbb8196.png)

## i know this should be in another ticket, but since i'm doing the current thing with identifying the warnings

# after
The buttons in the green zone, their context menus went down and i could access "set orientation"
The buttons in the red zone, their context menus went up and thru the top of the screen and i could **not** access "set orientation"
![image](https://user-images.githubusercontent.com/3880072/97865791-6187d800-1cd0-11eb-87f0-08c0c2dbc12a.png)

**Comment by kreezxil** [comment]
Need to point out that was full screen windowed. Absolute full screen "borderless" and the context menu is readable and goes down for the red zone.

**Comment by kreezxil** [comment]
# these are the droids you're looking for

## I was able to move the "customization" button because it was revealed, but these others in the red zone, i can't get to. to move them.

![image](https://user-images.githubusercontent.com/3880072/97867381-626e3900-1cd3-11eb-8f33-2f2d40b3b814.png)

## another log
https://gist.github.com/87d1132cd5282ecf730b154b56f4cfce

**Comment by P3rf3ctXZer0** [comment]
make sure this also gets pressed to 1.12.2

**Comment by Keksuccino** [comment]
Everything I add to the mod will be in all versions of it, if possible.

**Comment by Keksuccino** [comment]
> oh wow, FM thinks every button on that page is overlapping
It not just thinks that they are overlapping, they **are** overlapped, but invisible ^^
I have to say, this is by far the most annoying screen ever.
It doesn't open a new screen when clicking on "More World Options", but changes the visibility of the buttons needed for it and makes the previous buttons invisible. The positions of these buttons are the same, that's why they are overlapping.

I will try to fix this.

**Comment by Keksuccino** [comment]
I added a config option to turn of warnings as workaround for the log spam, but will keep try to find a good fix for this screen. But the way this menu is coded makes it nearly impossible to make it compatible with my customization engine.. I would need to override the whole screen to add full support :/ Will keep trying!

**Comment by kreezxil** [comment]
the way this menu is coded also makes me think you could add advanced
features by embracing it. Not sure what to call it, chained buttons?

**Comment by Keksuccino** [comment]
What exactly do you mean with "chained buttons"? :D

**Comment by kreezxil** [comment]
give us the power to make menus just like that messed up from Mojang. like
there's a bunch of buttons, they over lap. but they're invisible. Until you
click the one that is a prequalification for it.

**Comment by Keksuccino** [comment]
Can't do anything to fix this, I'm sorry.
